name: Android

on: [push]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: example

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Node
        uses: actions/setup-node@v1

      - uses: joschi/setup-jdk@v2
        with:
          java-version: '8' # The OpenJDK version to make available on the path
          architecture: 'x64' # defaults to 'x64'

      - name: Download Android Emulator Image
        run: |
          echo yes | $ANDROID_HOME/tools/bin/sdkmanager --channel=0 --verbose "system-images;android-28;default;x86_64"
          echo no | $ANDROID_HOME/tools/bin/avdmanager --verbose create avd --force --name "Pixel_API_28" --package "system-images;android-28;default;x86_64" --sdcard 200M --device 11
          $ANDROID_HOME/emulator/emulator -list-avds

      - name: Install node_modules
        run: |
          npm install
          npx jetify

      - name: Build for detox
        run: |
          npx detox build -c android.emu.release

      - name: Test Detox
        run: npx detox test -c android.emu.release --artifacts-location="e2e/__screenshots__" --take-screenshots="all" --headless
